name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

      - name: Build and Deploy
        uses: sma11black/hexo-action@v1.0.3
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         # PUBLISH_REPOSITORY: qq9694526/blog # The repository the action should deploy to.
          BRANCH: blog  # The branch the action should deploy to.
          PUBLISH_DIR: ./public # The folder the action should deploy.
